apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: chart3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chaser100/helm_ingress_nginx.git
    targetRevision: main
    path: chart3
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: app3

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
